import RandExp from "randexp";

// ─── Pattern Subset Checker ──────────────────────────────────────────────────
//
// Checks whether a regex pattern is a subset of another regex pattern
// via a sampling-based approach.
//
// Principle:
//   L(A) ⊆ L(B)  ⟺  ∀s ∈ L(A), s ∈ L(B)
//
// This cannot be formally proven for arbitrary ECMA-262 regexes
// (the problem is PSPACE-complete for pure regexes, and undecidable with
// extensions like backreferences).
//
// Pragmatic approach:
//   1. Generate N random strings matching the sub pattern (via `randexp`)
//   2. Verify that EVERY string also matches the sup pattern
//   3. If all match → return `true` (high confidence)
//   4. If at least one doesn't match → return `false` (certain)
//   5. If generation fails → return `null` (undetermined)
//
// Limitations:
//   - False positives are possible (but very unlikely with sufficient N)
//   - Does not handle regexes with complex backreferences
//   - `randexp` may generate biased strings (not uniformly distributed)
//
// To mitigate false positives, we use:
//   - A high sample count (200 by default)
//   - Multiple seeds to diversify generation
//   - A `null` fallback when in doubt

// ─── Configuration ───────────────────────────────────────────────────────────

/** Default number of generated samples */
const DEFAULT_SAMPLE_COUNT = 200;

/** Maximum length of strings generated by randexp */
const MAX_GENERATED_LENGTH = 100;

/** Maximum number of repetitions for unbounded quantifiers (*, +, {n,}) */
const MAX_REPETITION = 20;

// ─── Result Cache ────────────────────────────────────────────────────────────

/**
 * Cache of isPatternSubset results to avoid recomputing the same comparisons.
 * The key is `${subPattern}\0${supPattern}\0${sampleCount}`.
 */
const subsetCache = new Map<string, boolean | null>();

/**
 * Cache of compiled RegExp results to avoid recompilation.
 */
const regexCache = new Map<string, RegExp | null>();

/**
 * Cache of RandExp generators to avoid re-creation.
 */
const generatorCache = new Map<string, RandExp | null>();

/**
 * Clears internal caches. Useful for tests or memory management.
 */
export function clearPatternCaches(): void {
	subsetCache.clear();
	regexCache.clear();
	generatorCache.clear();
}

// ─── Trivial pattern detection (module-level constants) ──────────────────────

/**
 * Known universal patterns — match any string (or nearly any).
 * Defined at the module level to avoid recreating the Set on every call.
 */
const UNIVERSAL_PATTERNS: ReadonlySet<string> = new Set([
	".*",
	".+",
	"^.*$",
	"^.+$",
	"^.*",
	".*$",
	"^.+",
	".+$",
	"(?:.*)",
	"(?:.+)",
]);

/**
 * Anchored universal patterns — common variants that match everything.
 * Used for fast detection of universal supersets.
 */
const _ANCHORED_UNIVERSAL_REGEX =
	/^\^?\(?:\.\*\)?\$?$|^\^?\.\*\$?$|^\^?\.\+\$?$/;

// ─── Internal helpers ────────────────────────────────────────────────────────

/**
 * Creates a configured RandExp generator for a given pattern (with cache).
 *
 * @param pattern  The source regex pattern
 * @returns        The configured RandExp instance, or null if the pattern is invalid
 */
function createGenerator(pattern: string): RandExp | null {
	const cached = generatorCache.get(pattern);
	if (cached !== undefined) return cached;

	try {
		const randexp = new RandExp(pattern);
		randexp.max = MAX_REPETITION;
		generatorCache.set(pattern, randexp);
		return randexp;
	} catch {
		generatorCache.set(pattern, null);
		return null;
	}
}

/**
 * Compiles a pattern into a RegExp with error handling and cache.
 *
 * @param pattern  The regex pattern to compile
 * @returns        The compiled RegExp object, or null if invalid
 */
function compileRegex(pattern: string): RegExp | null {
	const cached = regexCache.get(pattern);
	if (cached !== undefined) return cached;

	try {
		const regex = new RegExp(pattern);
		regexCache.set(pattern, regex);
		return regex;
	} catch {
		regexCache.set(pattern, null);
		return null;
	}
}

/**
 * Checks whether a pattern is a universal superset (matches everything).
 * Used to short-circuit sampling when sup matches everything.
 */
function isUniversalSuperset(pattern: string): boolean {
	const trimmed = pattern.trim();
	if (trimmed === "" || UNIVERSAL_PATTERNS.has(trimmed)) return true;

	// Check variants with optional anchors
	// e.g.: "^(.*)$", "^(.+)$" etc.
	if (trimmed === "^(.*)$" || trimmed === "^(.+)$") return true;

	return false;
}

/**
 * Checks whether subPattern is a literal substring of supPattern
 * or whether sup is clearly broader (quick heuristics).
 * Returns true if sub ⊆ sup is guaranteed, null otherwise.
 */
function quickSubsetCheck(
	_subPattern: string,
	supPattern: string,
): boolean | null {
	// If sup is universal → everything is a subset
	if (isUniversalSuperset(supPattern)) return true;

	// If sub is an exact literal pattern (anchored string without metacharacters)
	// and sup contains a character class or quantifier that encompasses it,
	// we cannot easily determine this → null
	return null;
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Checks whether the language of pattern `sub` is a subset of the language
 * of pattern `sup` via sampling.
 *
 * `sub ⊆ sup` means: every string matching `sub` also matches `sup`.
 *
 * Ternary contract:
 *   - `true`  → all sampled strings from sub match sup
 *               (high confidence, not a formal proof)
 *   - `false` → at least one string from sub does NOT match sup
 *               (certain — it's a concrete counter-example)
 *   - `null`  → cannot determine (invalid pattern, generation failed)
 *
 * @param subPattern    The regex pattern of the sub schema
 * @param supPattern    The regex pattern of the sup schema
 * @param sampleCount   Number of samples (default: 200)
 * @returns             `true`, `false`, or `null`
 *
 * @example
 * ```ts
 * isPatternSubset("^[a-z]{3}$", "^[a-z]+$");      // true  — 3 letters ⊆ 1+ letters
 * isPatternSubset("^[a-z]+$", "^[0-9]+$");         // false — letters ⊄ digits
 * isPatternSubset("^[a-z]+$", "^[a-z]{3}$");       // false — "ab" matches sub but not sup
 * isPatternSubset("invalid[", "^[a-z]+$");          // null  — invalid pattern
 * ```
 */
export function isPatternSubset(
	subPattern: string,
	supPattern: string,
	sampleCount: number = DEFAULT_SAMPLE_COUNT,
): boolean | null {
	// ── Identity: same pattern → always a subset ──
	if (subPattern === supPattern) return true;

	// ── Cache lookup ──
	const cacheKey = `${subPattern}\0${supPattern}\0${sampleCount}`;
	const cached = subsetCache.get(cacheKey);
	if (cached !== undefined) return cached;

	// ── Quick checks before sampling ──
	const quick = quickSubsetCheck(subPattern, supPattern);
	if (quick !== null) {
		subsetCache.set(cacheKey, quick);
		return quick;
	}

	// ── Compile the sup pattern ──
	const supRegex = compileRegex(supPattern);
	if (supRegex === null) {
		subsetCache.set(cacheKey, null);
		return null;
	}

	// ── Create the generator for sub ──
	const generator = createGenerator(subPattern);
	if (generator === null) {
		subsetCache.set(cacheKey, null);
		return null;
	}

	// ── Generate and verify samples lazily ──
	// Instead of generating all samples first then verifying them,
	// we generate and verify one by one to allow early termination
	// as soon as a counter-example is found.
	const seen = new Set<string>();
	let validSamples = 0;
	let attempts = 0;
	const maxAttempts = sampleCount * 3; // Avoid infinite loops

	while (validSamples < sampleCount && attempts < maxAttempts) {
		attempts++;
		const sample = generator.gen();

		// Validate that the sample is usable
		if (typeof sample !== "string" || sample.length > MAX_GENERATED_LENGTH) {
			continue;
		}

		// Deduplicate samples
		if (seen.has(sample)) {
			continue;
		}
		seen.add(sample);
		validSamples++;

		// ── Immediate verification against sup ──
		// Early termination as soon as a counter-example is found
		if (!supRegex.test(sample)) {
			// Counter-example found → sub ⊄ sup (certain)
			subsetCache.set(cacheKey, false);
			return false;
		}
	}

	// If no samples could be generated → undetermined
	if (validSamples === 0) {
		subsetCache.set(cacheKey, null);
		return null;
	}

	// All samples match → sub ⊆ sup (high confidence)
	subsetCache.set(cacheKey, true);
	return true;
}

/**
 * Checks whether two patterns are equivalent (accept the same language)
 * via bidirectional sampling.
 *
 * `A ≡ B` means: `A ⊆ B` AND `B ⊆ A`.
 *
 * @param patternA     First regex pattern
 * @param patternB     Second regex pattern
 * @param sampleCount  Number of samples per direction (default: 200)
 * @returns            `true`, `false`, or `null`
 */
export function arePatternsEquivalent(
	patternA: string,
	patternB: string,
	sampleCount: number = DEFAULT_SAMPLE_COUNT,
): boolean | null {
	if (patternA === patternB) return true;

	const aSubB = isPatternSubset(patternA, patternB, sampleCount);
	if (aSubB === null) return null;
	if (aSubB === false) return false;

	const bSubA = isPatternSubset(patternB, patternA, sampleCount);
	if (bSubA === null) return null;

	return bSubA;
}

/**
 * Checks whether a pattern is "trivially universal" — i.e., it matches
 * every string (or nearly every). Useful for detecting patterns that
 * add no real constraint.
 *
 * Patterns detected as universal:
 *   - `.*`
 *   - `.+` (matches everything except the empty string)
 *   - `^.*$`
 *   - `^.+$`
 *   - Empty or whitespace-only patterns
 *
 * @param pattern  The pattern to check
 * @returns        `true` if the pattern is trivial/universal
 */
export function isTrivialPattern(pattern: string): boolean {
	const trimmed = pattern.trim();
	if (trimmed === "") return true;

	return UNIVERSAL_PATTERNS.has(trimmed);
}
